<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>e34f0c59-eeef-42c3-9c31-9f9c64fca701</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeLLM.DataAccess\FreeLLM.DataAccess.csproj" />
    <ProjectReference Include="..\FreeLLM.Plugins\FreeLLM.Plugins.csproj" />
    <ProjectReference Include="..\FreeLLM.Client\FreeLLM.Client.csproj" />
    <PackageReference Include="AspNet.Security.OAuth.Apple" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.32.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Plugins\Example1.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Plugins\Example2.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Plugins\Example3.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Plugins\LoginWithPrompts.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Plugins\UserUpdate.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Plugins\HelloWorld.assemblies">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Plugins\HelloWorld.plugin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Plugins\HelloWorld\HelloWorld.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Plugins\Plugins.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
